export function getCountryDisplay(countryCode: string): string {
  const countryMap: Record<string, string> = {
    ID: "Indonesia 🇮🇩",
    MY: "Malaysia 🇲🇾",
    SG: "Singapore 🇸🇬",
    PH: "Philippines 🇵🇭",
    TH: "Thailand 🇹🇭",
    VN: "Vietnam 🇻🇳",
    MM: "Myanmar 🇲🇲",
    KH: "Cambodia 🇰🇭",
    LA: "Laos 🇱🇦",
    BN: "Brunei 🇧🇳",
    TL: "Timor-Leste 🇹🇱",
    CN: "China 🇨🇳",
    TW: "Taiwan 🇹🇼",
    HK: "Hong Kong 🇭🇰",
    MO: "Macau 🇲🇴",
    JP: "Japan 🇯🇵",
    KR: "South Korea 🇰🇷",
    IN: "India 🇮🇳",
    PK: "Pakistan 🇵🇰",
    BD: "Bangladesh 🇧🇩",
    NP: "Nepal 🇳🇵",
    LK: "Sri Lanka 🇱🇰",
    SA: "Saudi Arabia 🇸🇦",
    AE: "United Arab Emirates 🇦🇪",
    IQ: "Iraq 🇮🇶",
    JO: "Jordan 🇯🇴",
    EG: "Egypt 🇪🇬",
    RU: "Russia 🇷🇺",
    TR: "Turkey 🇹🇷",
    KZ: "Kazakhstan 🇰🇿",
    UZ: "Uzbekistan 🇺🇿",
    BR: "Brazil 🇧🇷",
    MX: "Mexico 🇲🇽",
    AR: "Argentina 🇦🇷",
    CL: "Chile 🇨🇱",
    CO: "Colombia 🇨🇴",
    PE: "Peru 🇵🇪",
    US: "United States 🇺🇸",
    CA: "Canada 🇨🇦",
    FR: "France 🇫🇷",
    DE: "Germany 🇩🇪",
    IT: "Italy 🇮🇹",
    ES: "Spain 🇪🇸",
    GB: "United Kingdom 🇬🇧",
    NL: "Netherlands 🇳🇱",
    PL: "Poland 🇵🇱",
    RO: "Romania 🇷🇴",
    ZA: "South Africa 🇿🇦",
    NG: "Nigeria 🇳🇬",
    KE: "Kenya 🇰🇪",
    GH: "Ghana 🇬🇭",
    AU: "Australia 🇦🇺",
    NZ: "New Zealand 🇳🇿",
  };

  return countryMap[countryCode.toUpperCase()] || countryCode;
}